version: '2.1'

services:
  frontend:
    build: frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      REACT_APP_PUBLISHED_BACKEND_PORT: backend:8080
 
  backend:
    build: backend
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      PORT: 8080 
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"